// application/react/src/components/FileUpload.jsx
import { useState, useRef } from 'react'
import './FileUpload.css'

function FileUpload({ onFilesUploaded }) {
  const [isDragging, setIsDragging] = useState(false)
  const [selectedFiles, setSelectedFiles] = useState([])
  const [uploading, setUploading] = useState(false)
  const fileInputRef = useRef(null)

  const handleDragEnter = (e) => {
    e.preventDefault()
    e.stopPropagation()
    setIsDragging(true)
  }

  const handleDragLeave = (e) => {
    e.preventDefault()
    e.stopPropagation()
    setIsDragging(false)
  }

  const handleDragOver = (e) => {
    e.preventDefault()
    e.stopPropagation()
  }

  const handleDrop = (e) => {
    e.preventDefault()
    e.stopPropagation()
    setIsDragging(false)

    const files = Array.from(e.dataTransfer.files)
    setSelectedFiles(files)
  }

  const handleFileSelect = (e) => {
    const files = Array.from(e.target.files)
    setSelectedFiles(files)
  }

  const handleUpload = async () => {
    if (selectedFiles.length === 0) return

    setUploading(true)

    try {
      const apiBaseUrl = import.meta.env.VITE_API_BASE_URL || 'http://localhost:8080'

      // Upload each file
      for (const file of selectedFiles) {
        const formData = new FormData()
        formData.append('file', file)

        const response = await fetch(`${apiBaseUrl}/upload/file`, {
          method: 'POST',
          body: formData,
        })

        if (!response.ok) {
          throw new Error(`Failed to upload ${file.name}`)
        }
      }

      // Call the callback with uploaded files
      onFilesUploaded(selectedFiles)

      // Clear selected files
      setSelectedFiles([])

      // Reset file input
      if (fileInputRef.current) {
        fileInputRef.current.value = ''
      }
    } catch (error) {
      console.error('Upload error:', error)
      alert(`Upload failed: ${error.message}`)
    } finally {
      setUploading(false)
    }
  }

  const handleRemoveFile = (indexToRemove) => {
    setSelectedFiles(files => files.filter((_, index) => index !== indexToRemove))
  }

  const handleBrowseClick = () => {
    fileInputRef.current?.click()
  }

  return (
    <div className="file-upload-container">
      <div
        className={`drop-zone ${isDragging ? 'dragging' : ''}`}
        onDragEnter={handleDragEnter}
        onDragOver={handleDragOver}
        onDragLeave={handleDragLeave}
        onDrop={handleDrop}
        onClick={handleBrowseClick}
      >
        <input
          ref={fileInputRef}
          type="file"
          multiple
          onChange={handleFileSelect}
          className="file-input"
        />

        <div className="drop-zone-content">
          <svg
            className="upload-icon"
            fill="none"
            stroke="currentColor"
            viewBox="0 0 24 24"
            xmlns="http://www.w3.org/2000/svg"
          >
            <path
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeWidth={2}
              d="M7 16a4 4 0 01-.88-7.903A5 5 0 1115.9 6L16 6a5 5 0 011 9.9M15 13l-3-3m0 0l-3 3m3-3v12"
            />
          </svg>

          <h3>Drag and drop files here</h3>
          <p>or click to browse</p>
        </div>
      </div>

      {selectedFiles.length > 0 && (
        <div className="selected-files">
          <h3>Selected Files ({selectedFiles.length})</h3>
          <ul className="file-list">
            {selectedFiles.map((file, index) => (
              <li key={index} className="file-item">
                <div className="file-info">
                  <span className="file-name">{file.name}</span>
                  <span className="file-size">{formatFileSize(file.size)}</span>
                </div>
                <button
                  className="remove-btn"
                  onClick={() => handleRemoveFile(index)}
                  aria-label="Remove file"
                >
                  ×
                </button>
              </li>
            ))}
          </ul>

          <button
            className="upload-btn"
            onClick={handleUpload}
            disabled={uploading}
          >
            {uploading ? 'Uploading...' : 'Upload Files'}
          </button>
        </div>
      )}
    </div>
  )
}

function formatFileSize(bytes) {
  if (bytes === 0) return '0 Bytes'
  const k = 1024
  const sizes = ['Bytes', 'KB', 'MB', 'GB']
  const i = Math.floor(Math.log(bytes) / Math.log(k))
  return Math.round(bytes / Math.pow(k, i) * 100) / 100 + ' ' + sizes[i]
}

export default FileUpload

// application/vue/src/components/FileUpload.vue
<template>
  <div class="file-upload">
    <div class="upload-area" @dragover.prevent @drop.prevent="handleDrop">
      <input
        type="file"
        ref="fileInput"
        @change="handleFileSelect"
        :multiple="multiple"
        :accept="accept"
        class="file-input"
      />
      <div class="upload-content" @click="triggerFileSelect">
        <div v-if="!files.length">
          <p class="upload-icon">📁</p>
          <p class="upload-text">Click to select or drag and drop files here</p>
        </div>
        <div v-else class="file-list">
          <div v-for="(file, index) in files" :key="index" class="file-item">
            <span class="file-name">{{ file.name }}</span>
            <span class="file-size">{{ formatFileSize(file.size) }}</span>
            <button @click.stop="removeFile(index)" class="remove-btn">×</button>
          </div>
        </div>
      </div>
    </div>
    <button v-if="files.length" @click="uploadFiles" class="upload-btn" :disabled="uploading">
      {{ uploading ? 'Uploading...' : 'Upload Files' }}
    </button>
  </div>
</template>

<script>
export default {
  name: 'FileUpload',
  props: {
    multiple: {
      type: Boolean,
      default: true
    },
    accept: {
      type: String,
      default: ''
    },
    uploadUrl: {
      type: String,
      required: true
    }
  },
  data() {
    return {
      files: [],
      uploading: false
    }
  },
  methods: {
    triggerFileSelect() {
      this.$refs.fileInput.click()
    },
    handleFileSelect(event) {
      const selectedFiles = Array.from(event.target.files)
      this.addFiles(selectedFiles)
    },
    handleDrop(event) {
      const droppedFiles = Array.from(event.dataTransfer.files)
      this.addFiles(droppedFiles)
    },
    addFiles(newFiles) {
      if (this.multiple) {
        this.files = [...this.files, ...newFiles]
      } else {
        this.files = newFiles.slice(0, 1)
      }
      this.$emit('files-selected', this.files)
    },
    removeFile(index) {
      this.files.splice(index, 1)
      this.$emit('files-selected', this.files)
    },
    formatFileSize(bytes) {
      if (bytes === 0) return '0 Bytes'
      const k = 1024
      const sizes = ['Bytes', 'KB', 'MB', 'GB']
      const i = Math.floor(Math.log(bytes) / Math.log(k))
      return Math.round(bytes / Math.pow(k, i) * 100) / 100 + ' ' + sizes[i]
    },
    async uploadFiles() {
      if (!this.files.length) return

      this.uploading = true
      const formData = new FormData()

      this.files.forEach((file, index) => {
        formData.append(`file${index}`, file)
      })

      try {
        const response = await fetch(this.uploadUrl, {
          method: 'POST',
          body: formData
        })

        if (response.ok) {
          const result = await response.json()
          this.$emit('upload-success', result)
          this.files = []
          this.$refs.fileInput.value = ''
        } else {
          throw new Error('Upload failed')
        }
      } catch (error) {
        this.$emit('upload-error', error)
      } finally {
        this.uploading = false
      }
    }
  }
}
</script>

<style scoped>
.file-upload {
  width: 100%;
  max-width: 600px;
  margin: 0 auto;
}

.upload-area {
  border: 2px dashed #ccc;
  border-radius: 8px;
  padding: 40px;
  background-color: #f9f9f9;
  transition: all 0.3s ease;
}

.upload-area:hover {
  border-color: #42b983;
  background-color: #f0f9f4;
}

.file-input {
  display: none;
}

.upload-content {
  cursor: pointer;
  text-align: center;
}

.upload-icon {
  font-size: 48px;
  margin-bottom: 10px;
}

.upload-text {
  color: #666;
  margin: 0;
}

.file-list {
  text-align: left;
}

.file-item {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 10px;
  background-color: white;
  border-radius: 4px;
  margin-bottom: 8px;
}

.file-name {
  flex: 1;
  font-weight: 500;
}

.file-size {
  color: #666;
  margin: 0 10px;
  font-size: 0.9em;
}

.remove-btn {
  background: none;
  border: none;
  color: #ff4444;
  font-size: 24px;
  cursor: pointer;
  padding: 0 5px;
  line-height: 1;
}

.remove-btn:hover {
  color: #cc0000;
}

.upload-btn {
  margin-top: 20px;
  padding: 12px 30px;
  background-color: #42b983;
  color: white;
  border: none;
  border-radius: 4px;
  font-size: 16px;
  cursor: pointer;
  transition: background-color 0.3s ease;
}

.upload-btn:hover:not(:disabled) {
  background-color: #359268;
}

.upload-btn:disabled {
  background-color: #ccc;
  cursor: not-allowed;
}
</style>
